version: 2

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org,direct

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    dir: .
    main: ./cmd/dstp
    ldflags:
      - -s -w
      - -X github.com/DivyendraPatil/dstp/internal/version.Version={{.Version}}
      - -X github.com/DivyendraPatil/dstp/internal/version.Commit={{.ShortCommit}}
      - -X github.com/DivyendraPatil/dstp/internal/version.Date={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - completions/*
      - man/*

checksum:
  name_template: "checksums.txt"
