version: 2

env:
  - GOPROXY=https://proxy.golang.org
  - GOSUMDB=sum.golang.org

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
    dir: .
    main: ./cmd/dstp
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X github.com/DivyendraPatil/dstp/internal/version.Version={{.Version}}
      - -X github.com/DivyendraPatil/dstp/internal/version.Commit={{.ShortCommit}}
      - -X github.com/DivyendraPatil/dstp/internal/version.Date={{.CommitDate}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
      - completions/*
      - man/*

checksum:
  name_template: "checksums.txt"
