// Command gencompletions regenerates shell completions from dstp.CheckIDs().
// Run from the module root: go run ./cmd/gencompletions
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/DivyendraPatil/dstp/pkg/dstp"
)

const (
	zshPath  = "completions/dstp.zsh"
	bashPath = "completions/dstp.bash"
)

func main() {
	if _, err := os.Stat("go.mod"); err != nil {
		fatal(fmt.Errorf("run from module root (missing go.mod): %w", err))
	}
	if st, err := os.Stat("completions"); err != nil || !st.IsDir() {
		fatal(fmt.Errorf("missing completions/ directory"))
	}

	checks := strings.Join(dstp.CheckIDs(), " ")

	zsh := fmt.Sprintf(`#compdef dstp
# Generated by go run ./cmd/gencompletions — do not edit check list by hand.

local -a checks
checks=(%s)

_arguments -C \
  '(-a --addr)'{-a,--addr}'[target host]:host:' \
  '(-o --out)'{-o,--out}'[output format]:format:(plaintext json)' \
  '(-p)'{-p}'[ping count]:count:' \
  '(-t)'{-t}'[timeout seconds]:seconds:' \
  '--port[TLS/HTTPS port]:port:' \
  '--tcp-port[TCP port]:port:' \
  '--udp-port[UDP port]:port:' \
  '--http-port[HTTP port]:port:' \
  '--dns[custom DNS]:dns:' \
  '--doh[use DNS-over-HTTPS]' \
  '--doh-url[DoH URL]:url:' \
  '--doh-format[DoH format]:format:(rfc8484 json)' \
  '--doh-bootstrap[DoH bootstrap IP]:ip:' \
  '--method[HTTP method]:method:(GET HEAD)' \
  '--follow-redirects[follow redirects]' \
  '--insecure[skip TLS verify]' \
  '--extra[enable traceroute/whois/mtu]' \
  '--profile[check profile]:profile:(web mail dns api network full)' \
  '--skip[skip checks (comma-separated)]:checks:_values -s , check $checks' \
  '--config[config file]:file:_files' \
  '(-q --quiet)'{-q,--quiet}'[quiet]' \
  '(-v --version)'{-v,--version}'[version]' \
  '(-h --help)'{-h,--help}'[help]' \
  '*:host:'
`, checks)

	bashTmpl := `# bash completion for dstp
# Generated by go run ./cmd/gencompletions — do not edit check list by hand.
_dstp_checks="__CHECKS__"

_dstp() {
  local cur prev
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  local opts="-a --addr -o --out -p -t --port --tcp-port --udp-port --http-port --dns --doh --doh-url --doh-format --doh-bootstrap --method --follow-redirects --insecure --extra --profile --skip --config -q --quiet -v --version -h --help"
  case "${prev}" in
    -o|--out) COMPREPLY=( $(compgen -W "plaintext json" -- "${cur}") ); return ;;
    --method) COMPREPLY=( $(compgen -W "GET HEAD" -- "${cur}") ); return ;;
    --doh-format) COMPREPLY=( $(compgen -W "rfc8484 json" -- "${cur}") ); return ;;
    --profile) COMPREPLY=( $(compgen -W "web mail dns api network full" -- "${cur}") ); return ;;
    --skip)
      local prefix="" rest="${cur}"
      if [[ "${cur}" == *,* ]]; then
        prefix="${cur%,*},"
        rest="${cur##*,}"
      fi
      local comps
      comps=$(compgen -W "${_dstp_checks}" -- "${rest}")
      COMPREPLY=()
      local c
      for c in ${comps}; do
        COMPREPLY+=("${prefix}${c}")
      done
      return
      ;;
  esac
  if [[ "${cur}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
  fi
}
complete -F _dstp dstp
`
	bash := strings.ReplaceAll(bashTmpl, "__CHECKS__", checks)

	if err := os.WriteFile(zshPath, []byte(zsh), 0o600); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(bashPath, []byte(bash), 0o600); err != nil {
		fatal(err)
	}
	fmt.Printf("wrote %s\nwrote %s\n", zshPath, bashPath)
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "gencompletions: %v\n", err)
	os.Exit(1)
}
